apply plugin: "org.sonarqube"

sonarqube {
    if (project.hasProperty("buildType") && project.hasProperty("flavorType")) {
        String buildType = project.property("buildType").toString()
        String flavorType = project.property("flavorType").toString()
        String fullAndroidVariant = flavorType + buildType.capitalize()

        androidVariant fullAndroidVariant
    }

    properties {
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.verbose", true
        property "sonar.java.binaries", "buildSrc/build/classes"
        property "sonar.language", "kotlin"
        property "sonar.projectVersion", "0.1"
        property "sonar.issuesReport.html.enable", "true"
        property "sonar.issuesReport.console.enable", "true"

        property "sonar.coverage.jacoco.xmlReportPaths", findAllReports()

        property "sonar.java.coveragePlugin", "jacoco"

        property "sonar.projectKey", "newshots-kmp"
        property "sonar.organization", "apoorvgupta25"
        property"sonar.host.url", "https://sonarcloud.io"
    }
}

def sonarModules = [
        ":app",
        ":core",
        ":domain",
//        ":data:database",
        ":data:datastore",
        ":data:network",
        ":feature:bookmark",
        ":feature:details",
        ":feature:home",
        ":feature:listing",
        ":feature:search",
        ":library:coroutines",
        ":library:designsystem",
        ":library:draftjskmp",
]

configure(sonarModules.collect { project(it) }) {
    sonarqube {
        skipProject = false
        properties {
            property("sonar.sources", "src/")
        }
    }
}

String findAllReports() {
    def file = "${rootProject.buildDir}/reports"

    def sonarEnabledProjects = rootProject.subprojects
        .findAll { p -> p.sonarqube.getProperties().get("skipProject") == false }
        *.name
        .collect { projectName -> "$file/jacocoTestReport-${projectName}.xml" }
        .join(",")

    return sonarEnabledProjects
}
