complexity:
  LongMethod:
    allowedLines: 80

comments:
  excludes: [ '**/test/**', '**/androidTest/**', '**/android-test/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt' ]
  DocumentationOverPrivateFunction:
    active: false
  DocumentationOverPrivateProperty:
    active: false
  UndocumentedPublicProperty:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicClass:
    active: false
  OutdatedDocumentation:
    active: false
  EndOfSentenceFormat:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

style:
  MaxLineLength:
    maxLineLength: 140
  BracesOnWhenStatements:
    active: false
  MagicNumber:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    excludes: [ '**/test/**', '**/androidTest/**', '**/android-test/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt' ]
  UnsafeCast:
    excludes: [ '**/test/**', '**/androidTest/**', '**/android-test/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt' ]

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
    excludes: [ '**/theme/**', '**/test/**', '**/androidTest/**', '**/android-test/**' ]
  FunctionNameMaxLength:
    excludes: [ '**/test/**', '**/androidTest/**', '**/android-test/**' ]
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
    excludes: [ '**/test/**', '**/androidTest/**', '**/android-test/**' ]
