name: Build Check

# Run this upon a pull-request to the main and dependencies branch.
on:
  pull_request:
    branches:
      - main
      - dependencies

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Checks
        run: ./gradlew ktlintCheck

      - name: Build Project
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew test

  build-ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build iOS app
        run: xcodebuild -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphonesimulator